# Generated by Django 4.2.6 on 2023-10-25 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Verdura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verduras', to='mercado.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Legume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legumes', to='mercado.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Laticínio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('quantidade', models.CharField(max_length=255)),
                ('preco', models.CharField(max_length=255)),
                ('categoria', models.ManyToManyField(related_name='laticínios', to='mercado.categoria')),
                ('marca', models.ManyToManyField(related_name='laticínios', to='mercado.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Fruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frutas', to='mercado.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Carne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('quantidade', models.CharField(max_length=255)),
                ('preco', models.CharField(max_length=255)),
                ('categoria', models.ManyToManyField(related_name='carnes', to='mercado.categoria')),
                ('marca', models.ManyToManyField(related_name='carnes', to='mercado.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('quantidade', models.CharField(max_length=255)),
                ('preco', models.CharField(max_length=255)),
                ('categoria', models.ManyToManyField(related_name='bebidas', to='mercado.categoria')),
                ('marca', models.ManyToManyField(related_name='bebidas', to='mercado.marca')),
            ],
        ),
    ]
