# Generated by Django 4.2.6 on 2023-10-27 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('mercado', '0002_carne_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='verdura',
            name='capa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
    ]
