# Generated by Django 4.2.5 on 2023-10-03 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0002_marca_rename_descricao_categoria_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laticínio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('quantidade', models.CharField(max_length=255)),
                ('preco', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laticínios', to='mercado.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laticínios', to='mercado.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Carne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('quantidade', models.CharField(max_length=255)),
                ('preco', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carnes', to='mercado.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carnes', to='mercado.marca')),
            ],
        ),
    ]
