# Generated by Django 4.2.7 on 2023-11-07 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('mercado', '0004_marca_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruta',
            name='capa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
    ]
