# Generated by Django 4.2.5 on 2023-10-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0004_fruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruta',
            name='quantidade',
        ),
    ]
