# Generated by Django 4.2.5 on 2023-10-10 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0006_legume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verdura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verduras', to='mercado.categoria')),
            ],
        ),
    ]
