# Generated by Django 4.2.5 on 2023-10-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0007_verdura'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='categorias',
            field=models.ManyToManyField(related_name='marcas', to='mercado.categoria'),
        ),
    ]
