# Generated by Django 4.2.7 on 2023-11-28 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0007_bebida_descricao_alter_bebida_preco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bebida',
            name='descricao',
        ),
    ]
