# Generated by Django 5.0 on 2023-12-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0008_remove_bebida_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='carne',
            name='descricao',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
