# Generated by Django 4.2.5 on 2023-10-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0008_marca_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='carne',
            name='marca',
        ),
        migrations.AddField(
            model_name='carne',
            name='marca',
            field=models.ManyToManyField(related_name='carnes', to='mercado.marca'),
        ),
    ]
