# Generated by Django 4.2.5 on 2023-10-10 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0009_remove_marca_categorias_remove_carne_marca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laticínio',
            name='marca',
        ),
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('quantidade', models.CharField(max_length=255)),
                ('preco', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bebidas', to='mercado.categoria')),
                ('marca', models.ManyToManyField(related_name='bebidas', to='mercado.marca')),
            ],
        ),
        migrations.AddField(
            model_name='laticínio',
            name='marca',
            field=models.ManyToManyField(related_name='laticínios', to='mercado.marca'),
        ),
    ]
