# Generated by Django 5.0 on 2023-12-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0009_carne_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebida',
            name='descricao',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fruta',
            name='descricao',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
