# Generated by Django 4.2.5 on 2023-10-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0010_remove_laticínio_marca_bebida_laticínio_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bebida',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='carne',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='laticínio',
            name='categoria',
        ),
        migrations.AddField(
            model_name='bebida',
            name='categoria',
            field=models.ManyToManyField(related_name='bebidas', to='mercado.categoria'),
        ),
        migrations.AddField(
            model_name='carne',
            name='categoria',
            field=models.ManyToManyField(related_name='carnes', to='mercado.categoria'),
        ),
        migrations.AddField(
            model_name='laticínio',
            name='categoria',
            field=models.ManyToManyField(related_name='laticínios', to='mercado.categoria'),
        ),
    ]
